import asyncio
import sys
import httpx
from app.main import app
from app.core.database import init_db, get_database

sys.stdout.reconfigure(encoding='utf-8')

async def run_full_verification():
    print("=" * 70)
    print("   CINEMATCH AI — COMPLETE SYSTEM AUDIT & PRODUCTION VERIFICATION")
    print("=" * 70)

    await init_db()
    db = get_database()

    # 1. MongoDB Database Audit
    total_movies = await db.movies.count_documents({})
    print(f"\n[PHASE 2 - MONGODB DATABASE AUDIT]")
    print(f"  - Total Movie Documents in Atlas: {total_movies}")
    assert total_movies >= 5000, f"Expected 5000+ movies in database, found {total_movies}"

    # Distinct language check
    languages = await db.movies.distinct("original_language")
    print(f"  - Distinct Original Languages in Atlas: {len(languages)}")
    print(f"  - Top Languages Sample: {languages[:15]}")

    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:

        # 2. Industry Search Verification
        print(f"\n[PHASE 5 - SEARCH ENGINE INDUSTRY QUERY AUDIT]")
        industries_to_test = [
            ("Tollywood", "te"),
            ("Bollywood", "hi"),
            ("Kollywood", "ta"),
            ("Mollywood", "ml"),
            ("Sandalwood", "kn"),
            ("Anime", "ja"),
            ("Korean", "ko"),
            ("Hollywood", "en")
        ]

        for query, expected_lang in industries_to_test:
            res = await client.get(f"/api/search?q={query}")
            assert res.status_code == 200, f"Search failed for {query}"
            data = res.json()
            items = data.get("items", [])
            total = data.get("total", 0)
            print(f"  - Query: '{query:<12}' | Total Matches: {total:>5} | First 3: {[m['title'] for m in items[:3]]}")
            assert total > 0, f"No results returned for industry query '{query}'!"

        # 3. Discover Endpoint Verification
        print(f"\n[PHASE 6 - DISCOVER & FILTERS AUDIT]")
        res_disc = await client.get("/api/movies/discover?page=1&per_page=20&language=te")
        assert res_disc.status_code == 200
        disc_data = res_disc.json()
        print(f"  - Discover Tollywood (Telugu) Movies Total: {disc_data['total']} | Page Items: {len(disc_data['items'])}")

        # 4. Recommendation Engine Industry Balance Audit
        print(f"\n[PHASE 8 - AI RECOMMENDATION INDUSTRY BALANCE AUDIT]")
        res_tollywood_rec = await client.get("/api/recommendations/mood/tollywood")
        assert res_tollywood_rec.status_code == 200
        rec_items = res_tollywood_rec.json().get("recommendations", [])
        rec_titles = [r["title"] for r in rec_items[:5]]
        print(f"  - Tollywood Recommendation Top 5: {rec_titles}")
        assert len(rec_items) > 0, "Tollywood recommendations failed!"

        res_bollywood_rec = await client.get("/api/recommendations/mood/bollywood")
        assert res_bollywood_rec.status_code == 200
        bolly_items = res_bollywood_rec.json().get("recommendations", [])
        bolly_titles = [b["title"] for b in bolly_items[:5]]
        print(f"  - Bollywood Recommendation Top 5: {bolly_titles}")
        assert len(bolly_items) > 0, "Bollywood recommendations failed!"

        # 5. Multi-Select Genre & Combined Filter Audit
        print(f"\n[PHASE 10 - MULTI-SELECT & COMBINED FILTER AUDIT]")
        res_multi = await client.get("/api/movies?genres=Action,Adventure&language=te")
        assert res_multi.status_code == 200
        multi_data = res_multi.json()
        print(f"  - Combined Multi-Select (Tollywood Action + Adventure) Total: {multi_data['total']} | Returned Page Items: {len(multi_data['items'])}")
        assert multi_data['total'] > 0, "Multi-select filter query returned 0 matches!"

        # 6. Recommendation Contextual Explanation Audit
        print(f"\n[PHASE 11 - CONTEXTUAL EXPLANATION AUDIT]")
        res_rec = await client.get("/api/recommendations/industry/tollywood")
        assert res_rec.status_code == 200
        rec_data = res_rec.json()
        first_exp = rec_data['recommendations'][0]['explanation'] if rec_data['recommendations'] else ""
        print(f"  - Sample Contextual Explanation: '{first_exp}'")
        assert "Highest ranked" not in first_exp, "Generic autogenerated text detected!"
        assert len(first_exp) > 5, "Recommendation explanation missing or empty!"

        # 7. Movie Details Routing Verification
        print(f"\n[PHASE 9 - MOVIE DETAILS ROUTING AUDIT]")
        res_movie = await client.get("/api/movies/77")
        assert res_movie.status_code == 200
        m_json = res_movie.json()
        movie_title = m_json.get("title")
        print(f"  - Movie ID 77 Details Returned Title: '{movie_title}' | Director: '{m_json.get('director')}'")
        assert movie_title == "Inception", f"Expected 'Inception' for ID 77, got '{movie_title}'"
        assert "director" in m_json, "Director field missing in movie details response!"
        assert "writers" in m_json, "Writers field missing in movie details response!"

        # 8. Authentication Pipeline Verification
        print(f"\n[PHASE 3 - AUTHENTICATION PIPELINE AUDIT]")
        test_email = "e2e_audit_user@cinematch.ai"
        test_user = "e2e_audit_user"
        test_pass = "Password123!"

        await db.users.delete_many({"email": test_email})

        # Register
        r_reg = await client.post("/api/auth/register", json={
            "email": test_email,
            "username": test_user,
            "password": test_pass
        })
        assert r_reg.status_code == 201, f"Registration failed: {r_reg.text}"

        # Login
        r_login = await client.post("/api/auth/login", json={
            "email": test_email,
            "password": test_pass
        })
        assert r_login.status_code == 200, f"Login failed: {r_login.text}"
        tokens = r_login.json()
        print(f"  - Authentication Registered & Logged In Successfully! User ID={tokens['user']['id']}")

        # Protected Profile
        headers = {"Authorization": f"Bearer {tokens['access_token']}"}
        r_me = await client.get("/api/auth/me", headers=headers)
        assert r_me.status_code == 200, "Protected endpoint /auth/me failed!"
        logged_in_username = r_me.json()["username"]
        print(f"  - Protected Endpoint GET /auth/me Verified! Username: {logged_in_username}")

        # 9. Review System Audit (Username Resolution, Edit, Delete)
        print(f"\n[PHASE 12 - REVIEW SYSTEM USERNAME & EDIT/DELETE AUDIT]")
        r_post_rev = await client.post("/api/users/movies/77/reviews", json={
            "content": "Masterpiece film with stellar visuals!",
            "contains_spoilers": False
        }, headers=headers)
        assert r_post_rev.status_code == 200, f"Posting review failed: {r_post_rev.text}"
        rev_data = r_post_rev.json()
        rev_id = rev_data["id"]
        assert rev_data["username"] == logged_in_username, f"Expected review username '{logged_in_username}', got '{rev_data.get('username')}'"

        # Fetch reviews for movie 77
        r_get_revs = await client.get("/api/users/movies/77/reviews")
        assert r_get_revs.status_code == 200
        revs_list = r_get_revs.json()
        matching_rev = next((r for r in revs_list if r["id"] == rev_id), None)
        assert matching_rev is not None, "Created review not found in movie review list"
        assert matching_rev["username"] == logged_in_username, f"Username resolution failed! Expected '{logged_in_username}', got '{matching_rev.get('username')}'"
        print(f"  - Posted Review Username Verified: '{matching_rev['username']}' (No 'User #X' placeholder!)")

        # Edit Review
        r_edit_rev = await client.put(f"/api/users/reviews/{rev_id}", json={
            "content": "Updated review content: Absolute sci-fi masterpiece!",
            "contains_spoilers": False
        }, headers=headers)
        assert r_edit_rev.status_code == 200, f"Updating review failed: {r_edit_rev.text}"
        assert r_edit_rev.json()["content"] == "Updated review content: Absolute sci-fi masterpiece!"
        print("  - Edit Review Endpoint Verified!")

        # Delete Review
        r_del_rev = await client.delete(f"/api/users/reviews/{rev_id}", headers=headers)
        assert r_del_rev.status_code == 200, f"Deleting review failed: {r_del_rev.text}"
        print("  - Delete Review Endpoint Verified!")

    print("\n" + "=" * 70)
    print("      ALL PHASES & ADVANCED SYSTEM AUDITS PASSED 100%")
    print("=" * 70)

if __name__ == "__main__":
    asyncio.run(run_full_verification())
